# -*- coding: utf-8 -*-
"""Task_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JFCeY5KOQ4wfOKx2KZjgtRf_Szp061mq
"""

class GreenZoneIndex:
    def __init__(self, territory_name, territory_area, green_zones):
      self.territory_name = territory_name
      self.territory_area = territory_area
      self.green_zones = green_zones

      self.green_index = self.calculate_green_index()

    def calculate_green_index(self):

      green_index = sum(self.green_zones) / self.territory_area
      
      return round(green_index * 100,2)

territory_name_1 = "Pushkin"
territory_area_2 = 28676
green_zones_3 = [302, 487, 420, 325, 471, 363, 404]
pushkin = GreenZoneIndex(territory_name=territory_name_1, territory_area=territory_area_2, green_zones=green_zones_3)


territory_name = "Pushkin"
territory_area = 28676
green_zones = [302, 487, 420, 325, 471, 363, 404]
index_1 = GreenZoneIndex(territory_name, territory_area, green_zones)
index_1.green_index

print("Индекс озеленения территории = " + str(index_1.green_index) + "%")